### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by tsdko** [zymtom/Discord-Cleanup-Bot#1]
Code without a license is implicitly copyrighted, which means it can't be used without explicit permission of the author.

Useful resources:
[Choose an open source license](http://choosealicense.com/)
[Pick a License, Any License](https://blog.codinghorror.com/pick-a-license-any-license/)

**Comment by zymtom** [comment]
I'm aware, I just haven't gotten around to adding a license as this was a really small project of mine. But thanks for alerting me, I'll add it under the MIT license.

**Comment by zymtom** [comment]
There we go, license added. I'm interested however, are you actually planning on using this? @tsudoko

**Comment by tsdko** [comment]
There was a derivative project I'd wanted to contribute to, but the author took it down when I asked them about the license for their changes. Thanks anyway, but I'm not sure if starting from scratch wouldn't be a better idea now that the actual repository I wanted to use is down and the code from it is copyrighted.
